services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Admin211
    ports:
     - "5432:5432"
    volumes:
     - ./pgdata:/var/lib/postgresql/data
  mongo: 
    image: mongo
    ports:
     - "27017:27017"
    volumes:   
     - mongodata:/var/lib/mongodb/data
  rabbitmq: 
    image: rabbitmq:3-management-alpine
    ports:
     - "15672:15672"
     - "5672:5672"
  auction-service:
    image: ghostmachine26/first5:latest
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=auctiondb;User Id=postgres;Password=Admin211;
      - IdentityServiceUrl=http://identity-service
    ports:
      - "7001:80"
    depends_on:
      - postgres
      - rabbitmq
  
  search-service:
    image: ghostmachine26/search-service:latest
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://mongo
      - AuctionServiceUrl=http://auction-service
    ports:
      - "7002:80"
    depends_on:
      - mongo
      - rabbitmq
  
  cheche-gateway:
    image: ghostmachine26/cheche-gateway:latest
    build:
      context: .
      dockerfile: CheChe.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6001:80"

  identity-service:
    image: ghostmachine26/identity-service:latest
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=identity;User Id=postgres;Password=Admin211;
    ports:
      - "5000:80"
    depends_on:
      - postgres
      
      

volumes:
    pgdata:
    mongodata:
  
